// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }




// "use client";

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import AnnouncementBanner from "@/components/sections/Banner";
// import { useEffect, useState } from "react";
// import Loader from "@/components/ui/Loader";
// // import Loader from "@/components/sections/Loader";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   const [loading, setLoading] = useState(true);

//   useEffect(() => {
//     const t = setTimeout(() => setLoading(false), 900); // 0.9s dikhega
//     return () => clearTimeout(t);
//   }, []);
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col bg-black text-white relative">
//         {/* <Loader/> */}
//         {/* <AnnouncementBanner 
//           badgeText="Coming soon"
//           title="IEEE HIT SB Full Stack Bootcamp"
//           ctaText="Join the waitlist"
//           ctaLink="/login"
//           secondaryText="Learn more"
//           secondaryLink="/events"
//         /> */}
//            {loading && (
//           <div className="fixed inset-0 z-100 flex items-center justify-center bg-black transition-opacity">
//             <Loader />
//           </div>
//         )}
//         <AnnouncementBanner />
//         {children}
//       </body>
//     </html>
//   );
// }



// "use client";

// import { useEffect, useState } from "react";
// import Loader from "@/components/ui/Loader";

// export default function SplashScreen() {
//   const [loading, setLoading] = useState(true);

//   useEffect(() => {
//     const t = setTimeout(() => setLoading(false), 900); // 0.9s dikhega
//     return () => clearTimeout(t);
//   }, []);

//   if (!loading) return null;

//   return (
//     <div className="fixed inset-0 z-100 flex items-center justify-center bg-black transition-opacity">
//       <Loader />
//     </div>
//   );
// }



// import type { Metadata } from "next";
// import "./globals.css";
// import SplashScreen from "@/components/SplashScreen"; // Adjust path if needed

// export const metadata: Metadata = {
//   title: "IEEE HIT SB",
//   description: "Advancing Technology for Humanity",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body className="antialiased">
//         <SplashScreen />
//         {children}
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import "./globals.css";
import SplashScreen from "@/components/SplashScreen";

export const metadata: Metadata = {
  title: "IEEE HIT SB",
  description: "Advancing Technology for Humanity",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <SplashScreen />
        {children}
      </body>
    </html>
  );
}